[pytest]

addopts=    --headed
            --v
            --browser=chromium
            --screenshot=only-on-failure
            --video=retain-on-failure
            --tracing=retain-on-failure
            --html=reports/myreports.html --self-contained-html --capture=tee-sys
            --alluredir=reports/allure-results
            --reruns
            --rerun-delay
-



#  By default 'test-results' folder will be created , where it can saved all SS,videos,and trace.zip file.

#one disadvantage of this particular approach is we cannot specify the names randomly.So video screenshot tracing everything is a built in names.